repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
        exclude: ^main/static/assets/
      - id: end-of-file-fixer
        exclude: ^main/static/assets/
      - id: pretty-format-json
        exclude: ^main/static/assets/
        args: [--autofix, --indent, '4', --no-sort]
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --indent, '2', --offset, '2']
        exclude: manage.py|^main/static/assets/
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.1
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        exclude: manage.py
        additional_dependencies:
          - django-stubs[compatible-mypy]
          - django-stubs-ext
          - django-bootstrap5
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-fix
        exclude: ^main/static/assets/
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [-I, .codespell_ignore.txt]
        exclude: ^main/static/assets/|^package-lock.json$
