# Generated by Django 5.2.1 on 2025-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
