# Generated by Django 5.2.4 on 2025-08-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skilllevel_description_skilllevel_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleUserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exampleuser')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skill')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.skilllevel')),
            ],
        ),
    ]
