# Generated by Django 5.2.4 on 2025-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_userskill_unique_user_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
