# Generated by Django 5.2.4 on 2025-09-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_skill_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="skill",
            name="description",
            field=models.TextField(),
        ),
    ]
