# Generated by Django 5.2.4 on 2025-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_category_description_alter_skill_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="skilllevel",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
