# Generated by Django 6.0.1 on 2026-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category_slug_skill_slug_alter_skilllevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
