# Generated by Django 6.0.1 on 2026-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_learningresource_provider_userproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='focus',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='short_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
