# Generated by Django 6.0.1 on 2026-02-19 16:58

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def populate_skill_level_short_description(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Populate the short_description field of existing SkillLevel records."""
    SkillLevel = apps.get_model("main", "SkillLevel")

    for skill_level in SkillLevel.objects.filter(short_description=""):
        description = skill_level.description.split("\n")[0]
        skill_level.short_description = description[:200]
        skill_level.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_skilllevel_focus_skilllevel_short_description"),
    ]

    operations = [
        migrations.RunPython(
            populate_skill_level_short_description,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
