# Generated by Django 6.0.1 on 2026-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_populate_skilllevel_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, default=1000)),
            ],
            options={
                'ordering': ('rank', 'name'),
            },
        ),
    ]
