# Generated by Django 6.0.1 on 2026-02-19 17:48

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.utils.text import slugify


def ensure_slugs_in_slugified_models(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Ensure slugs are populated for all categories and skills."""
    slugified_models = ["Category", "Skill", "Provider", "LearningResource", "Tool"]
    for model in slugified_models:
        Model = apps.get_model("main", model_name=model)

        for instance in Model.objects.all():
            if not instance.slug:
                slug = slugify(instance.name)
                if Model.objects.filter(slug=slug).exists():
                    slug = f"{slug}-{instance.id}"
                instance.slug = slug
                instance.save()


def populate_competency_domains(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Populate the CompetencyDomain model from existing Parent Category records."""
    Category = apps.get_model("main", "Category")
    CompetencyDomain = apps.get_model("main", "CompetencyDomain")

    for category in Category.objects.filter(parent_category__isnull=True):
        CompetencyDomain.objects.create(
            name=category.name,
            description=category.description,
            slug=category.slug,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_competencydomain'),
    ]

    operations = [
        migrations.RunPython(
            ensure_slugs_in_slugified_models,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            populate_competency_domains,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
