# Generated by Django 6.0.1 on 2026-02-19 18:01

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def populate_category_competency_domains(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Populate the competency_domain fields from existing Parent Category records."""
    Category = apps.get_model("main", "Category")
    CompetencyDomain = apps.get_model("main", "CompetencyDomain")

    for category in Category.objects.filter(parent_category__isnull=False):
        category.competency_domain = CompetencyDomain.objects.get(
            slug=category.parent_category.slug
        )
        category.save()


def populate_category_parent_categories(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Populate the parent_category fields from existing CompetencyDomains records."""
    Category = apps.get_model("main", "Category")

    for category in Category.objects.filter(competency_domain__isnull=False):
        category.parent_category = Category.objects.get(
            slug=category.competency_domain.slug
        )
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category_competency_domain_alter_all_slugs'),
    ]

    operations = [
        migrations.RunPython(
            populate_category_competency_domains,
            reverse_code=populate_category_parent_categories,
        ),
    ]
