# Generated by Django 6.0.1 on 2026-02-20 17:45

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def remove_categories_with_no_domain(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Removes the categories with no domain/parent since they are now Domains."""
    Category = apps.get_model("main", "Category")
    Category.objects.filter(competency_domain__isnull=True).delete()


def restore_categories_with_no_domain(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Restore the categories with no parent from the CompetencyDomains."""
    Category = apps.get_model("main", "Category")
    CompetencyDomain = apps.get_model("main", "CompetencyDomain")

    for domain in CompetencyDomain.objects.all():
        Category.objects.create(
            name=domain.name,
            description=domain.description,
            competency_domain=None,
            parent_category=None,
            slug=domain.slug,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_populate_category_competency_domains'),
    ]

    operations = [
        migrations.RunPython(
            remove_categories_with_no_domain,
            reverse_code=restore_categories_with_no_domain,
        ),
    ]
