# Generated by Django 6.0.1 on 2026-02-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_competencies_with_no_domain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Competency',
        ),
        migrations.AlterModelOptions(
            name='competency',
            options={'verbose_name_plural': 'competencies'},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='category',
            new_name='competency',
        ),
        migrations.RemoveField(
            model_name='competency',
            name='parent_category',
        ),
        migrations.AlterField(
            model_name='competency',
            name='competency_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competencydomain'),
        ),
    ]
