# Generated by Django 6.0.1 on 2026-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_category_competency_alter_competency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='kind',
            field=models.CharField(choices=[('tool', 'Tool'), ('methodology', 'Methodology'), ('behaviour', 'Behaviour'), ('language', 'Language')], default='tool', max_length=12),
        ),
    ]
