# Generated by Django 6.0.2 on 2026-03-12 15:37

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def remove_behaviours(
    apps: StateApps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Removes the categories with no domain/parent since they are now Domains."""
    Tool = apps.get_model("main", "Tool")
    Tool.objects.filter(kind="behaviour").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_tool_kind'),
    ]

    operations = [
        migrations.RunPython(
            remove_behaviours,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Tool, Language or Methodology', 'verbose_name_plural': 'Tools, Languages and Methodologies'},
        ),
        migrations.AlterField(
            model_name='tool',
            name='kind',
            field=models.CharField(choices=[('tool', 'Tool'), ('language', 'Language'), ('methodology', 'Methodology')], default='tool', max_length=12),
        ),
    ]
