# Generated by Django 6.0.2 on 2026-03-24 12:13

import os
import logging
import string
import secrets

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

logger = logging.getLogger(__name__)


def create_admin_user(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Create an admin user based off provided environment variables."""
    USERNAME = os.environ.get("ADMIN_USERNAME")
    EMAIL = os.environ.get("ADMIN_EMAIL")

    if not (USERNAME and EMAIL):
        logger.warning(
            "ADMIN_USERNAME and ADMIN_EMAIL not provided as environment variables."
        )
        return

    user = apps.get_model("main", "User")

    if (queryset := user.objects.filter(username=USERNAME, email=EMAIL)).exists():
        user = queryset.first()
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save()
        logger.info(f"Made existing user '{USERNAME}' an admin")
    elif user.objects.filter(username=USERNAME).exists():
        logger.error(f"Username '{USERNAME}' already used with non-matching email.")
    elif user.objects.filter(email=EMAIL).exists():
        logger.error(f"Email '{EMAIL}' already used with non-matching username.")
    else:
        logger.info(f"Creating new admin user: '{USERNAME}'")
        alphabet = string.ascii_letters + string.digits
        password = ''.join(secrets.choice(alphabet) for i in range(8))
        admin = user.objects.create_superuser(
            username=USERNAME,
            email=EMAIL,
            password=password,
        )
        admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_learningresource_language'),
    ]

    operations = [
        migrations.RunPython(
            create_admin_user,
            reverse_code=migrations.RunPython.noop,
        )
    ]
