# Generated by Django 6.0.2 on 2026-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_create_admin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ('rank', 'name'), 'verbose_name_plural': 'competencies'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('rank', 'name')},
        ),
        migrations.AddField(
            model_name='competency',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='skill',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=1000),
        ),
    ]
