# Generated by Django 6.0.2 on 2026-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_competency_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_tos',
            field=models.BooleanField(default=False, verbose_name='agreed to terms and conditions'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_agreed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date agreed'),
        ),
    ]
