# Generated by Django 6.0.2 on 2026-04-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_user_agreed_to_tos_user_date_agreed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tool',
            new_name='ToolLanguageMethodology',
        ),
    ]
