# Generated by Django 6.0.3 on 2026-04-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_tool_toollanguagemethodology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toollanguagemethodology',
            options={'verbose_name': 'Tool, language or methodology', 'verbose_name_plural': 'Tools, languages and methodologies'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='tools',
            field=models.ManyToManyField(blank=True, to='main.toollanguagemethodology', verbose_name='tools, languages and methodologies'),
        ),
        migrations.AlterField(
            model_name='toollanguagemethodology',
            name='kind',
            field=models.CharField(choices=[('tool', 'Computational tool'), ('language', 'Programming or data language'), ('methodology', 'Methodology')], default='tool', max_length=12),
        ),
    ]
