# Generated by Django 6.0.2 on 2026-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_tool_toollanguagemethodology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tools',
            field=models.ManyToManyField(blank=True, to='main.toollanguagemethodology', verbose_name='tools, languages and methodologies'),
        ),
        migrations.AlterField(
            model_name='toollanguagemethodology',
            name='kind',
            field=models.CharField(choices=[('tool', 'Computational Tool'), ('language', 'Programming or Data Language'), ('methodology', 'Methodology')], default='tool', max_length=12),
        ),
    ]
