# Generated by Django 6.0.3 on 2026-04-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_toollanguagemethodology_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproxy',
            options={'verbose_name': 'User skills profile'},
        ),
    ]
