# Generated by Django 6.0.6 on 2026-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_userproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_link', models.URLField(blank=True, max_length=500, null=True)),
                ('blog', models.URLField(blank=True, max_length=500, null=True)),
                ('contributors', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('-start_date', 'title'),
                'unique_together': {('title', 'start_date')},
            },
        ),
    ]
