name: Build and push Docker Image
description: Build and push the docker image. Save cache to registry with configurable values
inputs:
  github-token:
    description: The GITHUB_TOKEN
    required: true
  publish:
    description: Boolean to determine if this build is published to GHCR
    default: false
  cache-from-ref:
    description: Where to get the cache from (passed to the build and push action)

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Get image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: echo input
      shell: bash
      run: |
        echo "tags: ${{ inputs.cache-from-ref || steps.meta.outputs.tags }}"
        echo "publish: ${{ inputs.publish }}"
        echo "type=registry,ref=${{ steps.meta.outputs.tags }}"
        echo "${{ case(inputs.publish == true, 'type=registry,ref=${{ steps.meta.outputs.tags }}', 'type=gha,mode=max') }}"


    # - name: Build and push Docker image for the web app
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     cache-from: type=registry,ref=${{ inputs.cache-from-ref || steps.meta.outputs.tags }}
    #     cache-to: ${{ case(inputs.publish, 'type=registry,ref=${{ steps.meta.outputs.tags }}', 'type=gha,mode=max') }}
