name: Test and build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    timeout-minutes: 15
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: pip
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -e .

      - name: Run mypy
        run: mypy .

      - name: Run tests
        run: pytest --cov-report=xml

      - name: Upload coverage to Codecov
        if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'pre-commit-ci[bot]' && github.ref_type != 'tag'
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Install doc dependencies
        run: pip install -r doc-requirements.txt

      - name: Check that documentation builds cleanly with MkDocs
        if: matrix.os == 'ubuntu-latest'
        run: mkdocs build --strict
